package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend-gql/graph/generated"
	"backend-gql/graph/model"
	"context"
	"fmt"
)

// GetAllGroups is the resolver for the getAllGroups field.
func (r *queryResolver) GetAllGroups(ctx context.Context) ([]*model.Group, error) {
	panic(fmt.Errorf("not implemented: GetAllGroups - getAllGroups"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
