package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"backend-gql/graph/model"
	"context"
)

// GetAllProfiles is the resolver for the getAllProfiles field.
func (r *queryResolver) GetAllProfiles(ctx context.Context) ([]*model.Profile, error) {
	data := r.ProfilesCache.GetAllProfiles()

	return data, nil
}
