package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend-gql/graph/model"
	"context"
	"fmt"
	"log"
)

// GetAllProfiles is the resolver for the getAllProfiles field.
func (r *queryResolver) GetAllProfiles(ctx context.Context) ([]*model.Profile, error) {
	fmt.Println("Se ejecuta Get all")

	query := `
	SELECT PROFILE_ID, NAME, DESCRIPTION, ORDER_BY, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, IS_ACTIVE FROM C_PROFILES
	`
	var data []*model.Profile
	rows, err := r.DB.Query(query)
	if err != nil {
		log.Fatalf("Error ejecutando query: %v", err)
	}
	defer rows.Close()

	for rows.Next() {
		var p model.Profile

		if err := rows.Scan(&p.ProfileID, &p.Name,
			&p.Description, &p.OrderBy, &p.CreatedOn,
			&p.CreatedBy, &p.ModifiedOn, &p.ModifiedBy, &p.IsActive); err != nil {
			log.Println("Error al leer: ", err.Error())
			continue
		}
		data = append(data, &p)
	}

	return data, nil
}
