package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend-gql/graph/model"
	"context"
)

// GetAllTools is the resolver for the getAllTools field.
func (r *queryResolver) GetAllTools(ctx context.Context) ([]*model.Tool, error) {
	tools := r.ToolsCache.GetAllTools()

	return tools, nil
}
