package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"backend-gql/graph/generated"
	"backend-gql/graph/model"
	"context"
)

// Group is the resolver for the group field.
func (r *groupsProfilesResolver) Group(ctx context.Context, obj *model.GroupsProfiles) (*model.Group, error) {
	group := r.GroupsCache.GetGroupById(obj.GroupID)
	return &group, nil
}

// Profile is the resolver for the profile field.
func (r *groupsProfilesResolver) Profile(ctx context.Context, obj *model.GroupsProfiles) (*model.Profile, error) {
	profile := r.ProfilesCache.GetcProfilesById(obj.ProfileID)
	return &profile, nil
}

// GetAllGroupsProfiles is the resolver for the getAllGroupsProfiles field.
func (r *queryResolver) GetAllGroupsProfiles(ctx context.Context) ([]*model.GroupsProfiles, error) {
	elements := r.RGroupsProfiles.GetAllGroupsProfiles()
	return elements, nil
}

// GroupsProfiles returns generated.GroupsProfilesResolver implementation.
func (r *Resolver) GroupsProfiles() generated.GroupsProfilesResolver {
	return &groupsProfilesResolver{r}
}

type groupsProfilesResolver struct{ *Resolver }
