package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend-gql/graph/model"
	"context"
	"fmt"
)

// GetAllGroupsProfiles is the resolver for the getAllGroupsProfiles field.
func (r *queryResolver) GetAllGroupsProfiles(ctx context.Context) ([]*model.GroupsProfiles, error) {
	panic(fmt.Errorf("not implemented: GetAllGroupsProfiles - getAllGroupsProfiles"))
}
