package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend-gql/graph/generated"
	"backend-gql/graph/model"
	"backend-gql/internal/logs"
	"context"
	"fmt"
)

// Profile is the resolver for the profile field.
func (r *profilesToolsResolver) Profile(ctx context.Context, obj *model.ProfilesTools) (*model.Profile, error) {
	profile := r.ProfilesCache.GetcProfilesById(obj.ProfileID)
	return &profile, nil
}

// Tool is the resolver for the tool field.
func (r *profilesToolsResolver) Tool(ctx context.Context, obj *model.ProfilesTools) (*model.Tool, error) {
	tool := r.ToolsCache.GetToolsById(obj.ToolID)
	return &tool, nil
}

// UpdatePermissionCache is the resolver for the updatePermissionCache field.
func (r *queryResolver) UpdatePermissionCache(ctx context.Context) ([]*model.ProfilesTools, error) {
	data, err := r.RProfilesTools.UpdateMatrix(r.DB)
	if err != nil {
		logs.Error("resolver/rProfilesTools.resolver.go/UpdatePermissionCache", fmt.Sprintf("Error: %w", err))
		return nil, fmt.Errorf("error:", err)
	} else {
		logs.Debug("resolver/rProfilesTools.resolver.go/UpdatePermissionCache", "Matriz de permisos actualizada")
	}
	return data, err
}

// GetAllProfilesTools is the resolver for the getAllProfilesTools field.
func (r *queryResolver) GetAllProfilesTools(ctx context.Context) ([]*model.ProfilesTools, error) {
	elements := r.RProfilesTools.GetAllProfilesTools()
	return elements, nil
}

// ProfilesTools returns generated.ProfilesToolsResolver implementation.
func (r *Resolver) ProfilesTools() generated.ProfilesToolsResolver { return &profilesToolsResolver{r} }

type profilesToolsResolver struct{ *Resolver }
