package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend-gql/graph/model"
	"context"
	"fmt"
)

// GetAllUsersProfiles is the resolver for the getAllUsersProfiles field.
func (r *queryResolver) GetAllUsersProfiles(ctx context.Context) ([]*model.UsersProfiles, error) {
	return nil, fmt.Errorf("GetAllUsersProfiles resolver is not implemented yet")
}
