package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"backend-gql/graph/generated"
	"backend-gql/graph/model"
	"backend-gql/internal/auth"
	"context"
	"fmt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.InputRegisterUser) (*model.UserCreated, error) {
	var user model.UserCreated
	hash, _ := auth.HashPassword(input.Password)

	query := `
		INSERT INTO app.T_USERS (
			name,
			last_name,
			second_last_name,
			email,
			hash_password,
			created_on
		)
		VALUES ($1,$2,$3,$4,$5,NOW())
		RETURNING id, name, last_name, second_last_name, email, created_on, modified_on, is_active
	`
	err := r.DBAuth.QueryRow(query, input.Name, input.LastName, input.SecondLastName, input.Email, hash).Scan(
		&user.ID,
		&user.Name,
		&user.LastName,
		&user.SecondLastName,
		&user.Email,
		&user.CreatedOn,
		&user.ModifiedOn,
		&user.IsActive,
	)
	if err != nil {
		return nil, fmt.Errorf("error insertando usuario: %w", err)
	}
	return &user, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
