package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"backend-gql/graph/model"
	"context"
	"fmt"
)

// Empleado is the resolver for the Empleado field.
func (r *queryResolver) Empleado(ctx context.Context) ([]*model.Empleado, error) {
	return nil, fmt.Errorf("Empleado resolver is not implemented yet")
}

// GetAllEmpleados is the resolver for the getAllEmpleados field.
func (r *queryResolver) GetAllEmpleados(ctx context.Context) ([]*model.Empleado, error) {
	return nil, fmt.Errorf("GetAllEmpleados resolver is not implemented yet")
}
