package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"backend-gql/graph/model"
	"context"
	"fmt"
)

// LoginUser is the resolver for the loginUser field.
func (r *queryResolver) LoginUser(ctx context.Context, input model.InputLoginUser) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: LoginUser - loginUser"))

	//var payloadData model.PayloadData

	/*
		INSERT INTO tabla (col1, col2)
		VALUES (valor1, valor2)
		ON CONFLICT (col_unica)
		DO UPDATE SET col2 = EXCLUDED.col2;
					type PayloadData{
				  profiles:[Int]!
				  name:String!
				  last_name:String!
				}
				type AuthPayload{
				    access_token:String!
				    refresh_token:String!
				}
	*/
}

// RefreshToken is the resolver for the refresh_token field.
func (r *queryResolver) RefreshToken(ctx context.Context, tokenRefresh string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: RefreshToken - refresh_token"))
}
