package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"backend-gql/graph/generated"
	"backend-gql/graph/model"
	"context"
	"fmt"
)

// CreateEmpleado is the resolver for the createEmpleado field.
func (r *mutationResolver) CreateEmpleado(ctx context.Context, input model.InputEmpleado) (*model.Empleado, error) {
	return nil, fmt.Errorf("CreateEmpleado resolver is not implemented yet")
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
