// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Empleado struct {
	ID     string `json:"id"`
	Nombre string `json:"nombre"`
}

type Group struct {
	GroupID     string  `json:"group_id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	OrderBy     *string `json:"order_by,omitempty"`
	CreatedOn   *string `json:"created_on,omitempty"`
	CreatedBy   *string `json:"created_by,omitempty"`
	ModifiedOn  *string `json:"modified_on,omitempty"`
	ModifiedBy  *string `json:"modified_by,omitempty"`
	IsActive    *bool   `json:"is_active,omitempty"`
}

type GroupsProfiles struct {
	GroupID    string  `json:"group_id"`
	ProfileID  string  `json:"profile_id"`
	CreatedOn  *string `json:"created_on,omitempty"`
	CreatedBy  *string `json:"created_by,omitempty"`
	ModifiedOn *string `json:"modified_on,omitempty"`
	ModifiedBy *string `json:"modified_by,omitempty"`
	IsActive   *bool   `json:"is_active,omitempty"`
}

type Mutation struct {
}

type Profile struct {
	ProfileID   string  `json:"profile_id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	OrderBy     *string `json:"order_by,omitempty"`
	CreatedOn   *string `json:"created_on,omitempty"`
	CreatedBy   *string `json:"created_by,omitempty"`
	ModifiedOn  *string `json:"modified_on,omitempty"`
	ModifiedBy  *string `json:"modified_by,omitempty"`
	IsActive    *bool   `json:"is_active,omitempty"`
}

type ProfilesTools struct {
	ProfileID  string   `json:"profile_id"`
	Profile    *Profile `json:"profile"`
	ToolID     string   `json:"tool_id"`
	Tool       *Tool    `json:"tool"`
	CreatedOn  *string  `json:"created_on,omitempty"`
	CreatedBy  *string  `json:"created_by,omitempty"`
	ModifiedOn *string  `json:"modified_on,omitempty"`
	ModifiedBy *string  `json:"modified_by,omitempty"`
	IsActive   *bool    `json:"is_active,omitempty"`
	Operations *string  `json:"operations,omitempty"`
}

type Query struct {
}

type Tool struct {
	ToolID        string  `json:"tool_id"`
	ToolIDFather  *string `json:"tool_id_Father,omitempty"`
	Name          *string `json:"name,omitempty"`
	Description   *string `json:"description,omitempty"`
	OrderBy       *string `json:"order_by,omitempty"`
	CreatedOn     *string `json:"created_on,omitempty"`
	CreatedBy     *string `json:"created_by,omitempty"`
	ModifiedOn    *string `json:"modified_on,omitempty"`
	ModifiedBy    *string `json:"modified_by,omitempty"`
	IsActive      *bool   `json:"is_active,omitempty"`
	Configuration *string `json:"configuration,omitempty"`
	Path          *string `json:"path,omitempty"`
}

type UsersProfiles struct {
	GroupID    string  `json:"group_id"`
	ProfileID  string  `json:"profile_id"`
	CreatedOn  *string `json:"created_on,omitempty"`
	CreatedBy  *string `json:"created_by,omitempty"`
	ModifiedOn *string `json:"modified_on,omitempty"`
	ModifiedBy *string `json:"modified_by,omitempty"`
	IsActive   *bool   `json:"is_active,omitempty"`
}

type InputEmpleado struct {
	ID     string `json:"id"`
	Nombre string `json:"nombre"`
}

type InputGroup struct {
	GroupID     string  `json:"group_id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	OrderBy     *string `json:"order_by,omitempty"`
	CreatedBy   *string `json:"created_by,omitempty"`
	IsActive    *bool   `json:"is_active,omitempty"`
}

type InputGroupsProfiles struct {
	GroupID    string  `json:"group_id"`
	ProfileID  string  `json:"profile_id"`
	CreatedBy  *string `json:"created_by,omitempty"`
	IsActive   *bool   `json:"is_active,omitempty"`
	ModifiedBy *string `json:"modified_by,omitempty"`
}

type InputProfile struct {
	ProfileID   string  `json:"profile_id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	OrderBy     *string `json:"order_by,omitempty"`
	CreatedBy   *string `json:"created_by,omitempty"`
	IsActive    *bool   `json:"is_active,omitempty"`
}

type InputProfilesTools struct {
	ProfileID   string  `json:"profile_id"`
	ToolID      string  `json:"tool_id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	OrderBy     *string `json:"order_by,omitempty"`
	CreatedBy   *string `json:"created_by,omitempty"`
	Operations  *string `json:"operations,omitempty"`
	IsActive    *bool   `json:"is_active,omitempty"`
}

type InputUsersProfiles struct {
	UserID     string  `json:"user_id"`
	ProfileID  string  `json:"profile_id"`
	CreatedBy  *string `json:"created_by,omitempty"`
	IsActive   *bool   `json:"is_active,omitempty"`
	ModifiedBy *string `json:"modified_by,omitempty"`
}
